# Generated by Django 5.1.7 on 2025-08-14 16:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dm', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('khoi_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ncc', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sdt', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('dia_chi', models.TextField(blank=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(max_length=50, unique=True, verbose_name='Size')),
            ],
            options={
                'verbose_name_plural': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoi_tao', models.DateTimeField(auto_now_add=True)),
                ('cap_nhat', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('ma_sp', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('ten_sp', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá gốc')),
                ('giam_gia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá khuyến mãi')),
                ('is_active', models.BooleanField(default=True)),
                ('khoi_tao', models.DateTimeField(auto_now_add=True)),
                ('danhmuc', models.ManyToManyField(blank=True, related_name='sanphams', to='shoes.danhmuc')),
                ('nhacungcap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanphams', to='shoes.nhacungcap')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh', models.ImageField(upload_to='sanpham/')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='shoes.sanpham')),
            ],
            options={
                'verbose_name_plural': 'Hình Ảnh Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='SizeSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn')),
                ('sku', models.CharField(blank=True, max_length=150, null=True, verbose_name='SKU size')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_sp', to='shoes.sanpham')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.size')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm theo size',
                'unique_together': {('sanpham', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Chitietgiohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='shoes.giohang')),
                ('size_sanpham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes.sizesanpham')),
            ],
            options={
                'unique_together': {('gio_hang', 'size_sanpham')},
            },
        ),
    ]
