# Generated by Django 5.2.5 on 2025-09-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
