# Generated by Django 5.1.7 on 2025-09-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_sanpham_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhmuc',
            options={'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AddField(
            model_name='danhmuc',
            name='danhmuc_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_con', to='shoes.danhmuc'),
        ),
    ]
