# Generated by Django 5.2.5 on 2025-09-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_danhmuc_options_danhmuc_danhmuc_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesanpham',
            name='gia_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Giá tùy chỉnh'),
        ),
        migrations.AddField(
            model_name='sizesanpham',
            name='loai_gia',
            field=models.CharField(choices=[('none', 'Mặc định'), ('custom', 'Giá tùy chỉnh')], default="none", max_length=20),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='danhmuc_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm', to='shoes.danhmuc'),
        ),
    ]
