# Generated by Django 5.2.5 on 2025-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_sizesanpham_gia_custom_sizesanpham_loai_gia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizesanpham',
            name='loai_gia',
            field=models.CharField(choices=[('none', 'Mặc định'), ('custom', 'Giá tùy chỉnh')], default='none', max_length=20),
        ),
    ]
