# Generated by Django 5.2.5 on 2025-09-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_sizesanpham_loai_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU'),
        ),
    ]
