# Generated by Django 5.2.5 on 2025-09-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_alter_sanpham_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmuc',
            name='danhmuc_con',
        ),
        migrations.AddField(
            model_name='danhmuc',
            name='ncc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ncc_dm', to='shoes.nhacungcap'),
        ),
    ]
