# Generated by Django 5.2.5 on 2025-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_remove_danhmuc_danhmuc_con_danhmuc_ncc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmuc',
            name='ncc',
        ),
        migrations.AddField(
            model_name='danhmuc',
            name='ncc',
            field=models.ManyToManyField(blank=True, null=True, related_name='ncc_dm', to='shoes.nhacungcap'),
        ),
    ]
