# Generated by Django 5.2.5 on 2025-09-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_remove_danhmuc_ncc_danhmuc_ncc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesanpham',
            name='gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.sanpham'),
        ),
    ]
