# Generated by Django 5.2.5 on 2025-09-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_sizesanpham_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizesanpham',
            name='gia',
        ),
    ]
