# Generated by Django 5.2.5 on 2025-10-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_remove_sizesanpham_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='sizesanpham',
            name='sku',
        ),
    ]
