# Generated by Django 5.2.5 on 2025-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_remove_sanpham_sku_remove_sizesanpham_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='khoi_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
