# Generated by Django 5.2.5 on 2025-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_alter_sanpham_khoi_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmuc',
            name='ncc',
            field=models.ManyToManyField(blank=True, related_name='ncc_dm', to='shoes.nhacungcap'),
        ),
    ]
