# Generated by Django 5.2.5 on 2025-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_alter_sanpham_khoi_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietgiohang',
            name='don_gia',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
