# Generated by Django 5.2.5 on 2025-10-31 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_alter_chitietgiohang_don_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietgiohang',
            name='khoi_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
