# Generated by Django 5.2.5 on 2025-11-01 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_chitietgiohang_khoi_tao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('dia_chi', models.CharField(max_length=255)),
                ('phuong_thuc', models.CharField(choices=[('cod', 'thanh toán khi nhận hàng'), ('online', 'thanh toán qua ngân hàng')], default='cod', max_length=25)),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=25)),
                ('phi_ship', models.DecimalField(decimal_places=2, default=30000, max_digits=100)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoadon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chitiethoadon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.sizesanpham')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cthd', to='shoes.hoadon')),
            ],
        ),
    ]
